{
 "title": "QAN",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "SELECT DISTINCT service_name FROM pmm.metrics"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Queries by Average Execution Time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    fingerprint AS \"Query Fingerprint\",\n    avg(m_query_time_sum) AS \"Average Time (s)\"\nFROM \"pmm\".\"metrics\"\nWHERE \n    period_start >= $__fromTime AND period_start <= $__toTime AND\n    service_name = '$service_name'\nGROUP BY fingerprint\nORDER BY \"Average Time (s)\" DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top Queries by Execution Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    fingerprint AS \"Query\",\n    count() AS \"Execution Count\"\nFROM pmm.metrics\nWHERE \n    period_start >= $__fromTime AND period_start <= $__toTime AND\n    service_name = '$service_name'\nGROUP BY fingerprint\nORDER BY \"Execution Count\" DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Query Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  period_start,\n  COUNT(*) AS \"Query Count\"\nFROM pmm.metrics\nWHERE period_start >= $__fromTime\n  AND period_start <= $__toTime\n  AND service_name = '$service_name'\nGROUP BY period_start\nORDER BY period_start ASC\n"
    }
   ]
  },
  {
   "title": "Top Queries by Error",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n    fingerprint AS \"Query\",\n    sum(num_queries_with_errors) AS \"Total Errors\"\nFROM pmm.metrics\nWHERE \n    period_start >= $__fromTime AND period_start <= $__toTime AND\n    service_name = '$service_name'\nGROUP BY fingerprint\nORDER BY \"Total Errors\" DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Query Time Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  period_start,\n  SUM(m_query_time_sum) / SUM(m_query_time_cnt) AS \"Avg Query Time\",\n  MIN(m_query_time_min) AS \"Min Query Time\",\n  MAX(m_query_time_max) AS \"Max Query Time\",\n  MAX(m_query_time_p99) AS \"P99 Query Time\"\nFROM pmm.metrics\nWHERE period_start >= $__fromTime\n  AND period_start <= $__toTime\n  AND service_name = '$service_name'\nGROUP BY period_start\nORDER BY period_start ASC\n"
    }
   ]
  }
 ]
}