services:
  pmm-server:
    image: percona/pmm-server:2
    container_name: pmm-server
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - pmm-data:/srv
    restart: always
    networks:
      - pmm-network

  pg-service:
    image: postgres:14
    container_name: pg-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pmm_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-pg.sql:/docker-entrypoint-initdb.d/init-pg.sql
    ports:
      - "5432:5432"
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
      -c track_io_timing=on
    restart: always
    networks:
      - pmm-network

  pmm-client:
    build:
      context: .
      dockerfile: Dockerfile.pmm-client
    container_name: pmm-client
    environment:
      CLIENT_ADDRESS: pmm-client
      CLIENT_NAME: pg-client
      POSTGRES_PASSWORD: password
    depends_on:
      - pmm-server
      - pg-service
    networks:
      - pmm-network
    restart: always

volumes:
  pmm-data:
  postgres-data:

networks:
  pmm-network:
    driver: bridge
